language: cpp
compiler: gcc
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - mesa-common-dev

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  - cd ${DEPS_DIR}
  - travis_retry wget https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1-Linux-x86_64.tar.gz  
  - tar -xzvf cmake-3.17.1-Linux-x86_64.tar.gz >log1
  - mv cmake-3.17.1-Linux-x86_64 cmake_install
  - PATH=${DEPS_DIR}/cmake_install:${DEPS_DIR}/cmake_install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .